## 분단위 데이터 정제 : 60*[x] -> x값 원하는 시간(분) 입력

In [4]:
import pandas as pd
import os
from sqlalchemy import create_engine
import pymysql
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np
import statistics as st

login = 'mysql+pymysql://research:eggtec2022@220.82.71.110/mldata'
df = pd.read_sql("select * from wash_data ORDER BY `date` ASC",login)


YMD = pd.DataFrame()
YMD['date'] = df['date'].dt.strftime('%Y-%m-%d')
YMD = YMD.drop_duplicates(ignore_index = True)
start_date = YMD.iloc[0,0]
end_date = YMD.iloc[len(YMD)-1,0]


start_time = 0
end_time = 0
count = 1

column_name = ['day','start','end','count','left_mean','left_max','left_min','left_median','left_mode','right_mean','right_max','right_min','right_median','right_mode','diff_mean','diff_max','diff_min','diff_median','diff_mode'] 

new_df = pd.DataFrame()
MinExtract = pd.DataFrame()

df.set_index('date',inplace = True)


for x in range(len(YMD)):
    
    # 데이터의 날짜(%Y%M%D) 추출
    day = YMD.iloc[x,0]
    
    # 해당 날짜의 데이터 추출
    daydata = df.loc[day]
    
    # 추출한 데이터 넘파이리스트로 변환
    daydata.reset_index(inplace=True)
    daylistdata = daydata.to_numpy()
    daydata.set_index('date',inplace=True)
    
    for y in range(len(daydata)):
        
        end = daylistdata[y][0]
        end_time = end.timestamp()
        
        if y > 0:
                                    
            if start_time == 0 :
                start = daylistdata[y-1][0]
                start_time = start.timestamp()

                
                
###################################################################              
                
            if end_time - start_time >= 60 * 0.5 :

###################################################################  

                MinExtract = daydata.loc[start:end]
                MinExtract.reset_index(inplace=True)
                
                left_mean = MinExtract['left'].mean()
                left_max = MinExtract['left'].max()
                left_min = MinExtract['left'].min()
                left_mid = MinExtract['left'].median()
                left_mode = st.mode(MinExtract['left'])
                right_mean = MinExtract['right'].mean()
                right_max = MinExtract['right'].max()
                right_min = MinExtract['right'].min()
                right_mid = MinExtract['right'].median()
                right_mode = st.mode(MinExtract['right'])
                diff_mean = MinExtract['diff'].mean()
                diff_max = MinExtract['diff'].max()
                diff_min = MinExtract['diff'].min()
                diff_mid = MinExtract['diff'].median()
                diff_mode = st.mode(MinExtract['diff'])
                
                DATA = [(day,start,end,count,left_mean,left_max,left_min,left_mid,left_mode,right_mean,right_max,right_min,right_mid,right_mode,diff_mean,diff_max,diff_min,diff_mid,diff_mode)]
                Data = pd.DataFrame(DATA,columns=column_name)
                new_df = pd.concat([new_df,Data])
                
                start = daylistdata[y+1][0]
                start_time = start.timestamp()
                count = 1
            
            if y == len(daydata) - 1 :
                
                MinExtract = daydata.loc[start:end]
                MinExtract.reset_index(inplace=True)
                
                left_mean = MinExtract['left'].mean()
                left_max = MinExtract['left'].max()
                left_min = MinExtract['left'].min()
                left_mid = MinExtract['left'].median()
                left_mode = st.mode(MinExtract['left'])
                right_mean = MinExtract['right'].mean()
                right_max = MinExtract['right'].max()
                right_min = MinExtract['right'].min()
                right_mid = MinExtract['right'].median()
                right_mode = st.mode(MinExtract['right'])
                diff_mean = MinExtract['diff'].mean()
                diff_max = MinExtract['diff'].max()
                diff_min = MinExtract['diff'].min()
                diff_mid = MinExtract['diff'].median()
                diff_mode = st.mode(MinExtract['diff'])
                
                DATA = [(day,start,end,count,left_mean,left_max,left_min,left_mid,left_mode,right_mean,right_max,right_min,right_mid,right_mode,diff_mean,diff_max,diff_min,diff_mid,diff_mode)]
                Data = pd.DataFrame(DATA,columns=column_name)
                new_df = pd.concat([new_df,Data])
                
                start_time = 0
                count = 1
                
        count += 1

In [5]:
new_df

,day,start,end,count,left_mean,left_max,left_min,left_median,left_mode,right_mean,right_max,right_min,right_median,right_mode,diff_mean,diff_max,diff_min,diff_median,diff_mode
0,2021-12-21,2021-12-21 09:23:12,2021-12-21 09:23:42,31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,2021-12-21,2021-12-21 09:23:43,2021-12-21 09:24:13,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,2021-12-21,2021-12-21 09:24:14,2021-12-21 09:24:44,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,2021-12-21,2021-12-21 09:24:45,2021-12-21 09:25:15,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,2021-12-21,2021-12-21 09:25:16,2021-12-21 09:25:46,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2022-01-19,2022-01-19 17:48:45,2022-01-19 17:49:15,32,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
0,2022-01-19,2022-01-19 17:49:16,2022-01-19 17:49:46,32,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
0,2022-01-19,2022-01-19 17:49:47,2022-01-19 17:50:17,32,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
0,2022-01-19,2022-01-19 17:50:18,2022-01-19 17:50:48,32,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
0,2022-01-19,2022-01-19 17:50:49,2022-01-19 17:50:59,12,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0

In [6]:
from sqlalchemy import create_engine
import pandas as pd
import pymysql
login = 'mysql+pymysql://research:eggtec2022@220.82.71.110/mldata'
engine = create_engine(login)
new_df.to_sql(name = 'wash_data_6min 30sec', con = engine , if_exists = 'replace', index = False)